package server

import (
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strings"

	"github.com/Audacity88/eyrie/internal/project"
	"github.com/Audacity88/eyrie/internal/reviewops"
)

func (s *Server) handleCreateReviewTask(w http.ResponseWriter, r *http.Request) {
	var req reviewops.CreateTaskRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": "invalid request body"})
		return
	}
	if _, err := s.projectStore.Get(strings.TrimSpace(req.ProjectID)); err != nil {
		if errors.Is(err, project.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	t, err := s.reviewStore.CreateTask(req)
	if err != nil {
		writeJSON(w, http.StatusBadRequest, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusCreated, t)
}

func (s *Server) handleListReviewTasks(w http.ResponseWriter, r *http.Request) {
	projectID := strings.TrimSpace(r.URL.Query().Get("project_id"))
	tasks, err := s.reviewStore.ListTasks(projectID)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if tasks == nil {
		tasks = []reviewops.Task{}
	}
	writeJSON(w, http.StatusOK, tasks)
}

func (s *Server) handleGetReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, t)
}

func (s *Server) handleRunReviewTask(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	t, err := s.reviewStore.GetTask(id)
	if err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if t.Status == reviewops.StatusRunning {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already running"})
		return
	}
	if t.Status == reviewops.StatusPosted {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task already posted"})
		return
	}
	if t.Status == reviewops.StatusFailed {
		writeJSON(w, http.StatusConflict, map[string]string{"error": "task failed; create a new task"})
		return
	}
	if _, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusRunning); err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	// Step 1: Attempt to fetch source context if domain is GitHub.
	var fetchErr string
	if t.Domain == reviewops.DomainGitHub {
		if s.githubClient == nil {
			fetchErr = "GitHub client unavailable"
		} else {
			var sc *reviewops.SourceContext
			var err error
			switch t.Kind {
			case "triage_issue":
				sc, err = s.githubClient.FetchIssueContext(r.Context(), t.Repo, t.TargetNumber)
			default:
				// review_pr, rereview_pr, respond_reviewer all fetch PR context
				sc, err = s.githubClient.FetchPRContext(r.Context(), t.Repo, t.TargetNumber)
			}
			if err != nil {
				slog.Warn("source context fetch failed", "task", id, "error", err)
				fetchErr = err.Error()
			} else {
				ctxContent := sc.RenderMarkdown()
				if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{
					TaskID:  id,
					Kind:    reviewops.ArtifactKindSourceContext,
					Content: ctxContent,
				}); err != nil {
					slog.Warn("failed to persist source context artifact", "task", id, "error", err)
					fetchErr = "source context fetched but failed to persist: " + err.Error()
				}
			}
		}
	}

	// Step 2: Create the local stub draft artifact (always).
	draftContent := fmt.Sprintf("# Local stub draft\n\nThis draft was generated by the local deterministic stub runner.\n\n- project_id: `%s`\n- kind: `%s`\n- repo: `%s`\n- target_number: `%d`\n", t.ProjectID, t.Kind, t.Repo, t.TargetNumber)
	if fetchErr != "" {
		draftContent += fmt.Sprintf("\n> **Note**: Source context fetch failed: %s\n", fetchErr)
	}
	draftContent += "\nNo GitHub mutations were performed in this milestone."

	if _, err := s.reviewStore.CreateArtifact(reviewops.CreateArtifactRequest{TaskID: id, Kind: reviewops.ArtifactKindMarkdown, Content: draftContent}); err != nil {
		_, _ = s.reviewStore.UpdateTaskStatus(id, reviewops.StatusFailed)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}

	// Step 3: Mark task as draft_ready.
	updated, err := s.reviewStore.UpdateTaskStatus(id, reviewops.StatusDraftReady)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	writeJSON(w, http.StatusOK, updated)
}

func (s *Server) handleListReviewTaskArtifacts(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	if _, err := s.reviewStore.GetTask(id); err != nil {
		if errors.Is(err, reviewops.ErrNotFound) {
			writeJSON(w, http.StatusNotFound, map[string]string{"error": err.Error()})
			return
		}
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	arts, err := s.reviewStore.ListArtifactsByTask(id)
	if err != nil {
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": err.Error()})
		return
	}
	if arts == nil {
		arts = []reviewops.Artifact{}
	}
	writeJSON(w, http.StatusOK, arts)
}
